version: "3.9"

services:
  mongo:
    image: mongo:5
    volumes:
      - "mongo:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adsb
      MONGO_INITDB_ROOT_PASSWORD: adsb

volumes:
  mongo: